spring.application.name=tasks

#Clever cloud
spring.datasource.url=jdbc:mysql://uop3tea8p4odol1r:xnR1cmFlSmNECyLyBsk4@biqhtxk4kfr3rxhlnfxu-mysql.services.clever-cloud.com:3306/biqhtxk4kfr3rxhlnfxu

#Local DB
#spring.datasource.url=jdbc:mysql://localhost:3306/task_crud?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
#spring.datasource.username=fwaroch
#spring.datasource.password=Haslo_123

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=20000

spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

trello.api.endpoint.prod=https://api.trello.com/1
trello.api.username=filipwaroch2
trello.app.key=b30047ce26c6be6311ef2fa1f2b07a21
trello.app.token=ATTA77048f7650e7716c87ff374a7aa3952ed39da2c1259838f905a2d2d7a237cb1dE1B7626C


admin.mail=f.waroch@gmail.com
# EMAIL CONFIGURATION
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# ACTUATOR INFO
info.app.name=Tasks Application
info.app.description=Application has been created on Kodilla course!
info.app.version=1.0.0
info.app.owner.name=John
info.app.owner.surname=Doe
info.app.administrator.email=john.doe@test.com
info.app.address.street=Super Cool Street
info.app.address.number=42
info.app.company.name=TaskCrudAppCreator
info.app.company.goal=Our goal is to make the world a better place!
info.app.company.email=tasks@crud.com
info.app.company.phone=744489230